version: '3.9'
services:
    fizzbuzzapi:
        container_name: "fizzbuzzapi"
        image: "alexsosic/fizz-buzz-api:master"
        env_file: "docker-compose.env"
        ports:
        - "8000:8080"

    postgres:
        container_name: "postgres"
        image: "postgres:12"
        env_file: "docker-compose.env"
        volumes:
        - ./pgdata:/docker-entrypoint-initdb.d
        ports:
        - "5432:5432"
